### ISSUE TITLE
1.12 update.

### ISSUE THREAD

**Issue by TheIntelloBox** [MassiveCraft/MassiveCore#305]
Hi, 

MassiveCore, Factions... doesn't work on 1.12 ! :D 
https://hastebin.com/powayawoku.sql

Thanks !

-----

**_Edit by MarkehMe: please fill out the issue template bellow:_**

-----

**Factions and MassiveCore**

**Spigot 1.12, Java 8**

* Affected Plugin version: 2.11.0
* MassiveCore version: 2.11.0
* Spigot version: Spigot 1.12

**Steps to reproduce this bug**

  1. Install Spigot 1.12
  2. Restart the server and you will see the errors

**This error : https://hastebin.com/powayawoku.sql**

**The plugin should be updated to 1.12**

**Comment by Lohkdesgds** [comment]
Same problem here :O

**Comment by MarkehMe** [comment]
Hello, if you could please fill out the issue template.

I have edited your original comment, can you please edit it and fill it out. Specifically, fill out **Describe your environment**

**Comment by TheIntelloBox** [comment]
Done.

**Comment by NerdyPacman** [comment]
I also have this problem.

**Comment by magnusulf** [comment]
For 1.12 compatibility please use the newest versions (2.13) of the plugins. Does the error still persist then?

**Comment by TheIntelloBox** [comment]
Sorry but if you saw my errors, you will know that it doesn't work for me in 1.12.

**Comment by nexlemav** [comment]
Im having the exact same issue. Spigot 1.12 and MassiveCore 2.12.0 and nothing ever loads

**Comment by oloflarsson** [comment]
@TheIntelloBox - You are using Factions 2.11.0 in this error message: https://hastebin.com/powayawoku.sql

@magnusulf was suggesting that you update Factions and MassiveCore to version 2.12.0.

It seems however there is some kind of issue with 2.12.0 that we will have to fix.

**Comment by oloflarsson** [comment]
This is fixed in 2.12.1 😸.
